name: hola-mundo

# Controls when the workflow will run
on: [push]
jobs: 
  # This workflow contains a single job called "hola-mundo"
  hola-mundo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Definir variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
        
      - name: Correr script
        run: node hola_mundo.js
